// Code generated by bitwrap synth; DO NOT EDIT.
// Source schema: ERC020 ERC-020:1.0.0

package prover

import (
	"github.com/consensys/gnark/frontend"
	"github.com/consensys/gnark/std/hash/mimc"
)

// synthMimcHash hashes two field elements with MiMC-BN254.
// Package-local helper so generated circuits don't collide with prover/circuits.go.
func synthMimcHash(api frontend.API, a, b frontend.Variable) frontend.Variable {
	h, _ := mimc.NewMiMC(api)
	h.Write(a)
	h.Write(b)
	return h.Sum()
}

// MintSynthCircuit is generated from schema action "mint". Parity target: MintCircuit in prover/circuits.go.
type MintSynthCircuit struct {
	PreStateRoot  frontend.Variable `gnark:",public"`
	PostStateRoot frontend.Variable `gnark:",public"`
	Caller        frontend.Variable `gnark:",public"`
	To            frontend.Variable `gnark:",public"`
	Amount        frontend.Variable `gnark:",public"`

	Minter    frontend.Variable
	BalanceTo frontend.Variable
}

func (c *MintSynthCircuit) Define(api frontend.API) error {
	// Role check (Action.Roles contains "minter")
	api.AssertIsEqual(c.Caller, c.Minter)
	// Output arc: balances[to] += amount
	newBalance := api.Add(c.BalanceTo, c.Amount)
	postLeaf := synthMimcHash(api, c.To, newBalance)
	api.AssertIsEqual(postLeaf, c.PostStateRoot)
	return nil
}

// BurnSynthCircuit is generated from schema action "burn". Parity target: BurnCircuit in prover/circuits.go.
type BurnSynthCircuit struct {
	PreStateRoot  frontend.Variable `gnark:",public"`
	PostStateRoot frontend.Variable `gnark:",public"`
	From          frontend.Variable `gnark:",public"`
	Amount        frontend.Variable `gnark:",public"`

	BalanceFrom frontend.Variable

	PathElements [20]frontend.Variable
	PathIndices  [20]frontend.Variable
}

func (c *BurnSynthCircuit) Define(api frontend.API) error {
	// Range check: BalanceFrom - Amount fits in 64 bits (non-negative)
	diff := api.Sub(c.BalanceFrom, c.Amount)
	api.ToBinary(diff, 64)

	// Merkle membership: balances[from] = BalanceFrom at PreStateRoot
	leaf := synthMimcHash(api, c.From, c.BalanceFrom)
	current := leaf
	for i := 0; i < 20; i++ {
		api.AssertIsBoolean(c.PathIndices[i])
		left := api.Select(c.PathIndices[i], c.PathElements[i], current)
		right := api.Select(c.PathIndices[i], current, c.PathElements[i])
		current = synthMimcHash(api, left, right)
	}
	api.AssertIsEqual(current, c.PreStateRoot)

	// Post-state: balances[from] decremented
	newBalance := api.Sub(c.BalanceFrom, c.Amount)
	postLeaf := synthMimcHash(api, c.From, newBalance)
	api.AssertIsEqual(postLeaf, c.PostStateRoot)
	return nil
}
