// Code generated by bitwrap synth; DO NOT EDIT.
// Source schema: ERC020 ERC-020:1.0.0

package prover

import (
	"github.com/consensys/gnark/frontend"
	"github.com/consensys/gnark/std/hash/mimc"
)

// synthMimcHash hashes two field elements with MiMC-BN254.
// Package-local helper so generated circuits don't collide with prover/circuits.go.
func synthMimcHash(api frontend.API, a, b frontend.Variable) frontend.Variable {
	h, _ := mimc.NewMiMC(api)
	h.Write(a)
	h.Write(b)
	return h.Sum()
}

// MintSynthCircuit is generated from schema action "mint". Parity target: MintCircuit in prover/circuits.go.
type MintSynthCircuit struct {
	PreStateRoot  frontend.Variable `gnark:",public"`
	PostStateRoot frontend.Variable `gnark:",public"`
	Caller        frontend.Variable `gnark:",public"`
	To            frontend.Variable `gnark:",public"`
	Amount        frontend.Variable `gnark:",public"`

	Minter    frontend.Variable
	BalanceTo frontend.Variable
}

func (c *MintSynthCircuit) Define(api frontend.API) error {
	// Role check (Action.Roles contains "minter")
	api.AssertIsEqual(c.Caller, c.Minter)
	// Output arc: balances[to] += amount
	newBalance := api.Add(c.BalanceTo, c.Amount)
	postLeaf := synthMimcHash(api, c.To, newBalance)
	api.AssertIsEqual(postLeaf, c.PostStateRoot)
	return nil
}
